### PR TITLE
Onboard: FDA food dataset

### PR DESCRIPTION
**Pull request by nlarge-google**
## Description

Includes: 
fda_food.food_enforcement,
fda_food.food_events

## Checklist

Note: Delete items below that aren't applicable to your pull request.

- [x] Please merge this PR for me once it is approved.
- [x] If this PR adds or edits a dataset or pipeline, it was reviewed and approved by the Google Cloud Public Datasets team beforehand.
- [x] If this PR adds or edits a dataset or pipeline, I put all my code inside  `datasets/fda_food` and nothing outside of that directory.
- [x] This PR is appropriately labeled.

### CODE REVIEW

**Comment by nlarge-google** [comment]
@adlersantos Please review this codse at your earliest convenience.  Thanks!

**Review by adlersantos — CHANGES_REQUESTED** [review]
This PR uses too many images. Try reducing them, or using a single one for pipelines and transforms that have much in common.

**Comment by nlarge-google** [comment]
@adlersantos I have merged FDA into one dataset.  Please review.  Thanks!

**Review by adlersantos — APPROVED** [review]
Looks good!

**Pull request merged**
